################
### Settings ###
################

collection = "nightly-230306"

[idris2]
url     = "https://github.com/buzden/Idris2"
version = "0.6.0"
commit  = "791b0be61bd6e6ed5b738b4abcf1e317d9f8127d"

[install]
whitelist = [ "deptycheck-tests", "pil-tests", "deptycheck-docs" ]

##############
### Locals ###
##############

[custom.all.deptycheck]
type = "local"
path = "."
ipkg = "deptycheck.ipkg"
test = "tests/tests.ipkg"

[custom.all.pil]
type = "local"
path = "example"
ipkg = "pil.ipkg"
test = "tests/tests.ipkg"

[custom.all.docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

####################
### Thirdparties ###
####################

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/buzden/idris2-elab-util"
commit = "e2cd24824d2c215a88d7d160d73a25cc67ca9d28"
ipkg   = "elab-util.ipkg"

[custom.all.sop]
type   = "git"
url    = "https://github.com/buzden/idris2-sop"
commit = "a9efb67d23adf3808bfd887781586ef318c56f35"
ipkg   = "sop.ipkg"
