################
### Settings ###
################

[install]
whitelist = [ "deptycheck-docs", "pil-fun", "pil-dyn" ]

#######################
### Elab-util-extra ###
#######################

[custom.all.elab-util-extra]
type = "local"
path = "elab-util-extra"
ipkg = "elab-util-extra.ipkg"
test = "tests/tests.ipkg"

[custom.nightly-251009.fin-lizzie]
type   = "git"
url    = "https://github.com/UARTman/idris2-fin-lizzie"
commit = "latest:fix-eq"
ipkg   = "fin-lizzie.ipkg"

[custom.nightly-251007.collection-utils]
type   = "git"
url    = "https://github.com/buzden/idris2-collection-utils"
commit = "latest:master"
ipkg   = "collection-utils.ipkg"

##################
### DepTyCheck ###
##################

[custom.all.deptycheck]
type = "local"
path = "."
ipkg = "deptycheck.ipkg"
test = "tests/tests.ipkg"

[custom.all.docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

################
### Examples ###
################

[custom.all.sorted-list-tl-pred]
type = "local"
path = "examples/sorted-list-tl-pred"
ipkg = "sorted-list-tl-pred.ipkg"
test = "tests/tests.ipkg"

[custom.all.sorted-list-so-comp]
type = "local"
path = "examples/sorted-list-so-comp"
ipkg = "sorted-list-so-comp.ipkg"
test = "tests/tests.ipkg"

[custom.all.sorted-list-so-full]
type = "local"
path = "examples/sorted-list-so-full"
ipkg = "sorted-list-so-full.ipkg"
test = "tests/tests.ipkg"

[custom.all.covering-seq]
type = "local"
path = "examples/covering-seq"
ipkg = "covering-seq.ipkg"
test = "tests/tests.ipkg"

[custom.all.uniq-list]
type = "local"
path = "examples/uniq-list"
ipkg = "uniq-list.ipkg"
test = "tests/tests.ipkg"

[custom.all.deep-wide-tree]
type = "local"
path = "examples/deep-wide-tree"
ipkg = "deep-wide-tree.ipkg"
test = "tests/tests.ipkg"

[custom.all.sorted-tree-naive]
type = "local"
path = "examples/sorted-tree-naive"
ipkg = "sorted-tree-naive.ipkg"
test = "tests/tests.ipkg"

[custom.all.sorted-tree-indexed]
type = "local"
path = "examples/sorted-tree-indexed"
ipkg = "sorted-tree-indexed.ipkg"
test = "tests/tests.ipkg"

[custom.all.pil-reg]
type = "local"
path = "examples/pil-reg"
ipkg = "pil-reg.ipkg"
test = "tests/tests.ipkg"

[custom.all.pil-fun]
type = "local"
path = "examples/pil-fun"
ipkg = "pil-fun.ipkg"
test = "tests/tests.ipkg"

[custom.all.pil-dyn]
type = "local"
path = "examples/pil-dyn"
ipkg = "pil-dyn.ipkg"
test = "tests/tests.ipkg"
