################
### Settings ###
################

[install]
whitelist = [ "deptycheck-docs" ]

##################
### DepTyCheck ###
##################

[custom.all.deptycheck]
type = "local"
path = "."
ipkg = "deptycheck.ipkg"
test = "tests/tests.ipkg"

[custom.all.docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

################
### Examples ###
################

[custom.all.sorted-list]
type = "local"
path = "examples/sorted-list"
ipkg = "sorted-list.ipkg"
test = "tests/tests.ipkg"

[custom.all.sorted-tree-naive]
type = "local"
path = "examples/sorted-tree-naive"
ipkg = "sorted-tree-naive.ipkg"
test = "tests/tests.ipkg"

[custom.all.pil-reg]
type = "local"
path = "examples/pil-reg"
ipkg = "pil-reg.ipkg"
test = "tests/tests.ipkg"
