################
### Settings ###
################

collection = "nightly-230923"

[idris2]
url     = "https://github.com/buzden/Idris2"
commit  = "21079dabe1a4a9167fdda127af27e34eacb0d1dc"

[install]
whitelist = [ "deptycheck-tests", "pil-tests", "deptycheck-docs" ]

##############
### Locals ###
##############

[custom.all.deptycheck]
type = "local"
path = "."
ipkg = "deptycheck.ipkg"
test = "tests/tests.ipkg"

[custom.all.pil]
type = "local"
path = "examples/pil"
ipkg = "pil.ipkg"
test = "tests/tests.ipkg"

[custom.all.docs]
type = "local"
path = "docs"
ipkg = "docs.ipkg"

####################
### Thirdparties ###
####################

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/buzden/idris2-elab-util"
commit = "85279ff5b357ff01e946316c06351c1fc9b7f685"
ipkg   = "elab-util.ipkg"

[custom.all.sop]
type   = "git"
url    = "https://github.com/buzden/idris2-sop"
commit = "a9efb67d23adf3808bfd887781586ef318c56f35"
ipkg   = "sop.ipkg"
